default['master_dns'] = 'ec2-13-58-84-22.us-east-2.compute.amazonaws.com'
default['slave_dns'] = 'ec2-18-191-249-104.us-east-2.compute.amazonaws.com'
default['master_name'] = 'db-master'
default['slave_name'] = 'db-slave'
default['passwords_databag'] = 'passwords.json'
