default['master_dns'] = 'ec2-18-223-30-23.us-east-2.compute.amazonaws.com'
default['slave_dns'] = 'slave.com'
default['master_name'] = 'db-master'
default['slave_name'] = 'db-slave'
default['passwords_databag'] = 'passwords.json'
