---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: /Users/Kirill/Downloads/temp/EPAM-tasks/Chef/chef-repo/roles
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    data_bags_path: test/fixtures/default/data_bags
   # encrypted_data_bag_secret_key_path: '/Users/Kirill/Downloads/temp/EPAM-tasks/Chef/chef-repo/cookbooks/db/test/integration/default/encrypted_data_bag_secret'
    run_list:
      - role[db_server]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
